### ISSUE TITLE
Clear UI and Hide Emulator buttons on emulator screen are disabled

### ISSUE THREAD

**Issue by MrReilley** [shftgroup/gisst#123]
The buttons for clearing the UI and hiding the emulator currently do not do anything.

**Comment by ekaltman** [comment]
I think the Clear UI should be changed to "reset UI". The goal of the "clear" was to just erase all the temporary states / performances if you wanted to start over. However, since you can literally also just reload the page I don't know if that is necessary. 

The hide emulator should not be present on the frontend-web build so that will need a separate issue.

**Comment by ekaltman** [comment]
Add the above "clear" concern in #125

**Comment by ekaltman** [comment]
Added the hide emulator to a separate issue #126
